vue_comptes_single_admin:
  title: Les Comptes
  fields:
    Identifiant:
        name: id
        type: text
        display:
          - show_table
          - show_table
        placeholder: Ajouter un identifiant
        rule: no
    nom:
      name: nom
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no
    prenom:
      name: prenom
      type: textArea
      display:
        - show_table
        - show_form
      placeholder: Ajouter un prenom
      rule: no
    email:
      name: email
      type: text
      display:
        - hidden_table
        - show_form
      placeholder: Ajouter un email
      rule: no
    addresse:
      name: addresse
      type: text
      display:
        - hidden_table
        - show_form
      placeholder: Ajouter adresse
      rule: no
    isActive:
      name: Etat
      display:
            - show_table
            - hidden_form
      type: text
      placeholder: Ajouter un titre
      required: no
    linkedAbonnement:
      name: abonnement
      display:
            - show_table
            - hidden_form
      type: text
      modificateur: getInfoLinkedOrList 
      arguments: 
        - abonnements 
    linkedCommande:
      name: commande
      display:
            - show_table
            - hidden_form
      type: text
      modificateur: getInfoLinkedOrList 
      arguments: 
        - commandes 
    photoProfil:
      name: photoProfil 
      type: text
      modificateur: getUrl 
      arguments: 
        - uploads
        - single        
      display:
        - hidden_table
        - show_form
      placeholder: Ajouter photo profil
      rule: no         
    phone:
      name: phone
      type: text
      display:
        - hidden_table
        - show_form
      placeholder: Ajouter un phone
      rule: no                             
    dateCreation:
      name: Libellé
      display:
        - show_table
        - hidden_form
      type: text
      placeholder: Ajouter un titre
      required: no
      format:
        type: tab
        name: Détails => Détails
    dateLastModif:
      name: Libellé
      display:
            - hidden_table
            - hidden_form
      type: text
      placeholder: Ajouter un titre
      required: no
      format:
        type: tab
        name: Détails => Détails       
    action:
      name: Actions
      display:
        - show_table
        - hidden_form
      type: button   


