vue_attributs_single_admin:
  title: Les attributs
  fields:
    Identifiant:
      name: id
      type: text
      display:
        - show_table
        - hidden_form
      rule: no
      required: no
      placeholder: désignation
      format:
        type: simple
        name: nocategory => nocategory
    code:
      name: Code
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: no
      placeholder: code
      format:
        type: simple
        name: nocategory => nocategory


    fr_nom:
      name: Désignation
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes
      placeholder: Désignation
      format:
        type: simple
        name: nocategory => français (France)
    
    fr_slug:
      name: Slug
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes
      placeholder: Slug
      format:
        type: simple
        name: nocategory => français (France)
    
    fr_description:
      name: Description
      type: textarea
      display:
        - show_table
        - show_form
      rule: no
      required: yes
      placeholder: Description
      format:
        type: simple
        name: nocategory => français (France)

    en_nom:
      name: Désignation
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes
      placeholder: Désignation
      format:
        type: simple
        name: nocategory => anglais (États-Unis)
    
    en_slug:
      name: Slug
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes
      placeholder: Slug
      format:
        type: simple
        name: nocategory => anglais (États-Unis)
    
    en_description:
      name: Description
      type: textarea
      display:
        - show_table
        - show_form
      rule: no
      required: yes
      placeholder: Description
      format:
        type: simple
        name: nocategory => anglais (États-Unis) 
      