collections_multi:
  icon: cube
  title: Les collections
  titleAdd: Ajouter un collection
  titleDet: Détails un collection
  titleUpdate: Modifier un collection
  fields:
    Identifiant:
        name: id
        type: text
        display:
          - show_table
          - hidden_form
        placeholder: Ajouter un id 
        rule: no
        required: yes 
        format:
          type: tab
          name: nocategory => nocategory
          rule: no 
    titre:
      name: titre
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory

    description:
      name: description
      type: text
      display:
        - show_table
        - hidden_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory
        
    linkedCompte:
      name: By
      type: text
      modificateur: getInfoLinkedOrList 
      arguments: 
        - comptes           
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   
    categories:
      name: categories
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   

    tags:
      name: Tags
      type: text
      modificateur: getInfoLinkedOrList 
      arguments: 
        - tags           
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory

    photoCouverture:
      name: photoCouverture
      type: photo
      modificateur: getUrl 
      arguments: 
        - uploads
        - single         
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory
    logo:
      name: logo
      type: photo
      modificateur: getUrl 
      arguments: 
        - uploads
        - single         
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory
    isActive:
      name: isActive
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory

    statut:
      name: statut
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory