produits_multi:
  icon: cube
  title: Les produits
  titleAdd: Ajouter un produit
  titleDet: Détails produit
  titleUpdate: Modifier Produit
  fields:
    Identifiant:
      name: id
      type: text
      display:
        - show_table
        - hidden_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory
        rule: no 
    name:
      name: Name
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory
        rule: no     
    type:
      name: Type
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un type 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory
        rule: no    
    prix:
      name: Prix
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un prix 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory
        rule: no      
    quantite:
      name: Quantité
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter une quantité 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory
        rule: no 

    linkedRestaurant:
      name: linkedRestaurant
      modificateur: getInfoLinkedOrList 
      arguments: 
        - restaurants     
      type: text
      display:
        - hidden_table
        - hidden_form
      placeholder: Ajouter un linkedRestaurant
      rule: no          
    statut:
      name: statut
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no
    childrens:
      name: childrens
      modificateur: getInfoLinkedOrList 
      arguments: 
        - produits        
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un childrens
      rule: no

    dateCreation:
      name: Libellé
      display:
            - hidden_table
            - hidden_form
      type: text
      placeholder: Ajouter un titre
      
    dateLastModif:
      name: Libellé
      display:
            - hidden_table
            - hidden_form
      type: text
      placeholder: Ajouter un titre 