specialites_multi:
  title: Les specialites
  fields:
    Identifiant:
        name: id
        type: text
        display:
          - show_table
          - hidden_form
        placeholder: Ajouter un identifiant
        rule: no
    libelle:
      name: titre
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no
    description:
      name: description
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no     
    statut:
      name: statut
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no    
    isActive:
      name: is active
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no        
    image:
      name: Image
      modificateur: getUrl 
      arguments: 
        - uploads
        - single        
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no                 