menus_multi:
  title: Les menus
  fields:   
    Identifiant:
      name: id
      type: text
      display:
        - show_table
        - hidden_form
      placeholder: id
      format:
        type: tab
        name: Détails => Détails 
      rule: no
      required: no

    image:
      name: Image
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no  
      modificateur: getUrl 
      arguments: 
        - uploads
        - single     

    titre:
      name: titre
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no
    # description:
    #   name: description
    #   type: text
    #   display:
    #     - show_table
    #     - show_form
    #   placeholder: Ajouter un nom
    #   rule: no     
       
    # linkedRestaurant:
    #   name: Restaurant
    #   type: text
    #   display:
    #     - show_table
    #     - show_form
    #   placeholder: Ajouter un nom
    #   rule: no              
    #   modificateur: getInfoLinkedOrList 
    #   arguments: 
    #     - restaurants
    prix:
      name: prix
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no               
                           
        
    statut:
      name: Statut
      type: checkbox
      display:
        - show_table
        - show_form
      rule: no
      required: no
      placeholder: Activée
      format:
        type: tab
        name: Détails => Détails
    isActive:
      name: Etat
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no 
    menus:
      name: menu
      display:
            - hidden_table
            - hidden_form
      type: text
      
    action:
      name: Actions
      display:
        - show_table
        - hidden_form
      type: button    
