restaurants_single:
  title: Les restaurants
  fields:   
    Identifiant:
      name: id
      type: text
      display:
        - show_table
        - hidden_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   

    titre:
      name: titre
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   

    description:
      name: description
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   

    phone:
      name: description
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   

    email:
      name: email
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory       
                   
    photoCouverture:
      name: photoCouverture
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   
      modificateur: getUrl
      arguments:
        - uploads
        - single    

    adresse:
      name: adresse
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   

    ville:
      name: adresse
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   

    pays:
      name: adresse
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   

    codePostal:
      name: adresse
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   

    position:
      name: position
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   

    responsable:
      name: responsable
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   
      modificateur: getInfoLinkedOrList
      arguments:
        - comptes   

    logo:
      name: logo
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory 
      modificateur: getUrl
      arguments:
        - uploads
        - single    

    specialiteRestos:
      name: specialiteRestos
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   
      modificateur: getInfoLinkedOrList
      arguments:
        - specialites  

    horaireTravails:
      name: horaireTravails
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   

    tags:
      name: liste Tags
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory  
      modificateur: getInfoLinkedOrList
      arguments:
        - tags    


    dateCreation:
      name: Libellé
      display:
            - hidden_table
            - hidden_form
      type: text
      placeholder: Ajouter un titre
    dateLastModif:
      name: Libellé
      display:
            - hidden_table
            - hidden_form
      type: text
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   
    statut:
      name: statut
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   
