restaurants_multi:
  title: Les restaurants
  fields:   
    Identifiant:
      name: id
      type: text
      display:
        - show_table
        - hidden_form
      placeholder: id
      format:
        type: tab
        name: Détails => Détails 
      rule: no
      required: no  

    photoCouverture:
      name: Image
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no
      modificateur: getUrl 
      arguments: 
        - uploads
        - single 

    titre:
      name: titre
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no
    # description:
    #   name: description
    #   type: text
    #   display:
    #     - show_table
    #     - show_form
    #   placeholder: Ajouter un nom
    #   rule: no     
    phone:
      name: Téléphone
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no       
    email:
      name: email
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no                 
                   
       
    adresse:
      name: adresse
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no            
    # ville:
    #   name: adresse
    #   type: text
    #   display:
    #     - show_table
    #     - show_form
    #   placeholder: Ajouter un nom
    #   rule: no         
    # pays:
    #   name: adresse
    #   type: text
    #   display:
    #     - show_table
    #     - show_form
    #   placeholder: Ajouter un nom
    #   rule: no        
    # codePostal:
    #   name: adresse
    #   type: text
    #   display:
    #     - show_table
    #     - show_form
    #   placeholder: Ajouter un nom
    #   rule: no          
    # position:
    #   name: position
    #   type: text
    #   display:
    #     - show_table
    #     - show_form
    #   placeholder: Ajouter un nom
    #   rule: no                   
    # responsable:
    #   name: responsable
    #   type: text
    #   display:
    #     - show_table
    #     - show_form
    #   placeholder: Ajouter reponsable
    #   rule: no                  
    # logo:
    #   name: logo
    #   type: text
    #   display:
    #     - show_table
    #     - show_form
    #   placeholder: Ajouter logo
    #   rule: no                
    # specialiteRestos:
    #   name: specialiteRestos
    #   type: text
    #   display:
    #     - show_table
    #     - show_form
    #   placeholder: Ajouter logo
    #   rule: no         
    # horaireTravails:
    #   name: horaireTravails
    #   type: text
    #   display:
    #     - show_table
    #     - show_form
    #   placeholder: Ajouter logo
    #   rule: no              
    # tags:
    #   name: liste Tags
    #   type: text
    #   display:
    #     - show_table
    #     - show_form
    #   placeholder: Ajouter un nom
    #   rule: no                 

    # dateCreation:
    #   name: Libellé
    #   display:
    #         - hidden_table
    #         - hidden_form
    #   type: text
    #   placeholder: Ajouter un titre
    # dateLastModif:
    #   name: Libellé
    #   display:
    #         - hidden_table
    #         - hidden_form
    #   type: text
    #   placeholder: Ajouter un titre
    # statut:
    #   name: statut
    #   type: text
    #   display:
    #     - show_table
    #     - show_form
    #   placeholder: Ajouter un nom
    #   rule: no 
    
    statut:
      name: Statut
      type: checkbox
      display:
        - show_table
        - show_form
      rule: no
      required: no
      placeholder: Activée
      format:
        type: tab
        name: Détails => Détails
    isActive:
      name: Etat
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no 
    # linkedRestaurant:
    #   name: restaurant
    #   display:
    #         - hidden_table
    #         - hidden_form
    #   type: text
    #   modificateur: getInfoLinkedOrList 
    #   arguments: 
    #     - restaurants 
    action:
      name: Actions
      display:
        - show_table
        - hidden_form
      type: button    
