categories_single:
  title: Les categories
  fields:   
    Identifiant:
        name: id
        type: text
        display:
          - show_table
          - hidden_form
        placeholder: Ajouter un identifiant
        rule: no
        required: yes 
        format:
          type: tab
          name: nocategory => nocategory   
    libelle:
      name: titre
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   
        
    description:
      name: description
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   
      
    isActive:
      name: Etat
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   
    image:
      name: Image
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory  
       
    linkedRestaurant:
      name: linkedRestaurant
      type: text
      display:
        - hidden_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   
      modificateur: getInfoLinkedOrList 
      arguments: 
        - restaurants
    statut:
      name: statut
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory   
