categories_multi:
  title: Les catégories
  fields:   
    Identifiant:
      name: id
      type: text
      display:
        - show_table
        - hidden_form
      placeholder: id
      format:
        type: tab
        name: Détails => Détails 
      rule: no
      required: no  
    libelle:
      name: Intitulé
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no  
    couleur:
      name: Couleur
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no  

    isActive:
      name: Etat
      type: checkbox
      display:
        - show_table
        - show_form
      rule: no
      required: no
      placeholder: Activée
      format:
        type: tab
        name: Détails => Détails 

    statut:
      name: Statut
      type: checkbox
      display:
        - show_table
        - show_form
      rule: no
      required: no
      placeholder: Activée
      format:
        type: tab
        name: Détails => Détails 
        
   
    action:
      name: Actions
      display:
        - show_table
        - hidden_form
      type: button    
    
