collections_multi:
  title: Les collections
  fields:   
    Identifiant:
      name: id
      type: text
      display:
        - show_table
        - hidden_form
      placeholder: id
      format:
        type: tab
        name: Détails => Détails 
      rule: no
      required: no  

    logo:
      name: Image
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no
      modificateur: getUrl 
      arguments: 
        - uploads
        - single 

    titre:
      name: Intitulé
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no 
    
    linkedCompte:
      name: Propriétaire
      type: text
      modificateur: getDetails 
      arguments: 
        - comptes      
      display:
        - show_table
        - hidden_form
      placeholder: Ajouter link livreur 

    isActive:
      name: Etat
      type: checkbox
      display:
        - show_table
        - show_form
      rule: no
      required: no
      placeholder: Activée
      format:
        type: tab
        name: Détails => Détails 

    statut:
      name: Statut
      type: checkbox
      display:
        - show_table
        - show_form
      rule: no
      required: no
      placeholder: Activée
      format:
        type: tab
        name: Détails => Détails 
        
   
    action:
      name: Actions
      display:
        - show_table
        - hidden_form
      type: button    
    
