comptes_multi:
  title: Les comptes
  fields:   
    Identifiant:
        name: id
        type: text
        display:
          - show_table
          - hidden_form
        placeholder: Ajouter un identifiant
        rule: no
    nom:
      name: nom
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no
    prenom:
      name: prenom
      type: textArea
      display:
        - show_table
        - show_form
      placeholder: Ajouter un prenom
      rule: no
    email:
      name: email
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un code
      rule: no
    phone:
      name: Téléphone
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un telephone
      rule: no     
    statut:
      name: Statut
      type: checkbox
      display:
        - show_table
        - show_form
      rule: no
      required: no
      placeholder: Activée
      format:
        type: tab
        name: Détails => Détails
    isActive:
      name: Etat
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no 
      
    action:
      name: Actions
      display:
        - show_table
        - hidden_form
      type: button    
