menus_single: 
  icon: book
  title: Les menus
  titleAdd: Ajouter un menu
  titleDet: Détails un menu
  titleUpdate: Modifier un menu
  fields:
    Identifiant:
      name: A propos
      type: text
      display:
        - show_table
        - hidden_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: Détails => Détails

    titre:
      name: Désignation
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: Détails => Détails

    description:
      name: Description
      type: textarea
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: Détails => Détails   

    statut:
      name: Statut
      type: text
      display:
        - show_table
        - hidden_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: Détails => Détails
           
    linkedRestaurant:
      name: Restaurant
      type: text
      
      display:
        - hidden_table
        - hidden_form
      placeholder: Ajouter un nom
      required: no 
      format:
        type: tab
        name: Détails => Détails      
      modificateur: getInfoLinkedOrList
      arguments:
        - restaurants

    prix:
      name: Prix
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: Détails => Détails

    tags:
      name: Tags
      type: select++
      options:
        - option 1
        - option 2
        - option 3
        - option 4 
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: Tags => Tags
      modificateur: getInfoLinkedOrList
      arguments:
        - tags  

    categorie:
      name: Catégorie
      type: select++
      options:
        - option 1
        - option 2
        - option 3
        - option 4 
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: Catégorie => Catégorie
      modificateur: getInfoLinkedOrList
      arguments:
        - categories  


    tailles:
      name: Tailles
      type: select
      options:
        - option 1
        - option 2
        - option 3
        - option 4 
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name:  Tailles => Tailles
    prixT:
      name: Prix
      type: number
      options:
        - option 1
        - option 2
        - option 3
        - option 4 
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name:  Tailles => Tailles
    sauces:
      name: Sauces
      type: select
      options:
        - option 1
        - option 2
        - option 3
        - option 4 
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name:  Sauces => Sauces     
    prixS:
      name: Prix
      type: number
      options:
        - option 1
        - option 2
        - option 3
        - option 4 
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name:  Sauces => Sauces    
           
    viandes:
      name: Viandes
      type: select
      options:
        - option 1
        - option 2
        - option 3
        - option 4 
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name:  Viandes => Viandes 
    prixV:
      name: Prix
      type: number
      options:
        - option 1
        - option 2
        - option 3
        - option 4 
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name:  Viandes => Viandes    
    
    garnitures:
      name: Garniture
      type: select
      options:
        - option 1
        - option 2
        - option 3
        - option 4 
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name:  Garnitures => Garnitures  
    prixG:
      name: Prix
      type: number
      options:
        - option 1
        - option 2
        - option 3
        - option 4 
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name:  Garnitures => Garnitures    
             
    
    boisons:
      name: Boissons
      type: select
      options:
        - option 1
        - option 2
        - option 3
        - option 4 
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name:  Boissons => Boissons     
    
    prixB:
      name: Prix
      type: number
      options:
        - option 1
        - option 2
        - option 3
        - option 4 
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name:  Boissons => Boissons    
    

    image:
      name: Photo
      type: photo
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: Média => Média    