reclamations:
  title: Les reclamations
  fields:
    Identifiant:
        name: id
        type: text
        display:
          - show_table
          - hidden_form
        placeholder: Ajouter un identifiant
        rule: no
    linkedCompte:
      name: linked compte
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no
    message:
      name: message
      type: textArea
      display:
        - show_table
        - show_form
      placeholder: Ajouter un prenom
      rule: no
    linkedCommande:
      name: id commande
      type: text
      display:
        - hidden_table
        - show_form
      placeholder: Ajouter un code
      rule: no

    dateCreation:
      name: date de creation
      type: text
      display:
        - hidden_table
        - show_form
      placeholder: Ajouter un code
      rule: no      
    statut:
      name: statut
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un nom
      rule: no      