mouvement:
  title: mouvement
  fields:
    Identifiant:
        name: id
        type: text
        display:
          - show_table
          - hidden_form
        placeholder: Ajouter un identifiant
    linkedZoneStock:
        name: zone stock
        type: text
        display:
          - show_table
          - hidden_form
        placeholder: Ajouter zone de stock  
    linkedProduit:
        name: id produits
        type: text
        display:
          - show_table
          - hidden_form
        placeholder: Ajouter id produit        
    linkedTaille:
        name: taille
        type: text
        display:
          - show_table
          - hidden_form
        placeholder: Ajouter taille  
    linkedCouleur:
        name: couleur
        type: text
        display:
          - show_table
          - hidden_form
        placeholder: Ajouter couleur   
    quantite:
        name: quantite
        type: text
        display:
          - show_table
          - hidden_form
        placeholder: Ajouter quantite     
    linkedResponsable:
        name: quantite
        type: text
        display:
          - show_table
          - hidden_form
        placeholder: Ajouter quantite     
    typeAction:
        name: typeAction
        type: text
        display:
          - show_table
          - hidden_form
        placeholder: Ajouter type action           
    statut:
        name: statut
        type: text
        display:
          - show_table
          - hidden_form
        placeholder: Ajouter un statut  
        rule: no
        required: no

        format:
          type: tab
          name: nocategory => nocategory 