paiments:
  icon: payment
  title: Paiements
  titleAdd: Ajouter une mode de paiements
  titleUpdate: Modifier mode de paiement
  fields:
    Identifiant:
        name: id 
        type: text
        display:
          - show_table
          - hidden_form
        placeholder: Ajouter un identifiant
        rule: no
        required: no
        format:
          type: tab
          name: nocategory => Détails paiement
   
    code:
        name: Code
        type: text
        display:
          - show_table
          - show_form
        placeholder: Ajouter un code
        rule: no
        required: no
        format:
          type: tab
          name: nocategory => Détails paiement
    active:
      name: Publié ?
      type: checkbox
      display:
        - show_table
        - show_form
      rule: no
      required: yes
      placeholder: Activée
      format:
        type: tab
        name:  nocategory => Détails paiement

    type:
      name: Type
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes
      placeholder: Activée
      format:
        type: tab
        name:  nocategory => Configuration du passerelle
      
    clepub:
      name: Clé publiable
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes
      placeholder: Activée
      format:
        type: tab
        name:  nocategory => Configuration du passerelle

    clesecrete:
      name: Clé secrète
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes
      placeholder: Activée
      format:
        type: tab
        name:  nocategory => Configuration du passerelle

    fr_designation:
      name: Désignation
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes
      placeholder: Désignation
      format:
        type: tab
        name: Détails => français (France)
    
    fr_description:
      name: Description
      type: textarea
      display:
        - show_table
        - show_form
      rule: no
      required: yes
      placeholder: Description
      format:
        type: tab
        name: Détails => français (France)
            
    fr_instruction:
      name: Instruction
      type: textarea
      display:
        - show_table
        - show_form
      rule: no
      required: yes
      placeholder: Description
      format:
        type: tab
        name: Détails => français (France)
    
    en_designation:
      name: Désignation
      type: text
      display:
        - show_table
        - show_form
      rule: no
      required: yes
      placeholder: Désignation
      format:
        type: tab
        name: Détails => anglais (États-Unis)
    
    en_description:
      name: Description
      type: textarea
      display:
        - show_table
        - show_form
      rule: no
      required: yes
      placeholder: Description
      format:
        type: tab
        name: Détails => anglais (États-Unis)
            
    en_instruction:
      name: Instruction
      type: textarea
      display:
        - show_table
        - show_form
      rule: no
      required: yes
      placeholder: Description
      format:
        type: tab
        name: Détails => anglais (États-Unis)
    

    
    