panier:
  title: Les paniers
  fields:
    Identifiant:
        name: id
        type: text
        display:
          - show_table
          - hidden_form
        placeholder: Ajouter un identifiant
    linkedCompte:
      name: link compte
      type: text
      display:
          - hidden_table
          - hidden_form
      placeholder: Ajouter un identifiant
    linkedCommande:
      name: link commande
      type: text
      display:
        - show_table
        - hidden_form
      placeholder: Ajouter un link commande
    listeProduits:
      name: link produit
      type: text
      display:
        - show_table
        - hidden_form
      placeholder: Ajouter link produit
    quantite:
      name: quantite
      type: text
      display:
        - show_table
        - hidden_form
      placeholder: Ajouter un quantite    
    prixHT:
      name: prixHT
      type: text
      display:
          - hidden_table
          - hidden_form
      placeholder: Ajouter prixHT
    prixTTC:
      name: prixTTC
      type: text
      display:
          - hidden_table
          - hidden_form
      placeholder: Ajouter un prixTTC
    remise:
      name: remise
      type: text
      display:
          - hidden_table
          - hidden_form
      placeholder: Ajouter un remise
    statut:
      name: etat
      type: text
      display:
          - hidden_table
          - hidden_form
      placeholder: Ajouter un etat      
                      
  popupAdd:
    titre: Ajouter un document
  popupDelete:
    titre: Supprimer document
    contenu: Êtes-vous sûr de vouloir supprimer ce document
  popupUpdate:
    titre: Modifier document
