promotions:
  icon: in cart
  title: Les promotions
  titleAdd: Ajouter une promotion
  titleDet: Détails une promotion
  titleUpdate: Modifier une promotion
  fields:
    Identifiant:
      name: id
      type: text
      display:
        - show_table
        - hidden_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory
    name:
      name: Nom
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory

    linkedRestaurant:
      name: link resto
      type: text
      display:
          - hidden_table
          - hidden_form
      placeholder: Ajouter un resto
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory

    type:
      name: Type
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory

    dateDebut:
      name: Date de début
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory

    dateFin:
      name: Date fin
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory

    value:
      name: value
      type: text
      display:
          - hidden_table
          - hidden_form
      placeholder: Ajouter un resto   
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory

    link:
      name: link
      type: text
      display:
          - hidden_table
          - hidden_form
      placeholder: Ajouter un link  
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory  
            
    photoCouverture:
      name: Photo de couverture
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory

    isActive:
      name: Etat
      type: text
      display:
        - show_table
        - hidden_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory

    statut:
      name: Statut
      type: text
      display:
        - show_table
        - hidden_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory