trajetcamion:
  icon: truck
  title: Les camions
  titleAdd: Ajouter un camion
  titleDet: Détails camion
  titleUpdate: Modifier camion
  fields:
    Identifiant:
      name: id
      type: text
      display:
        - show_table
        - hidden_form
      placeholder: Ajouter un id 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory
        rule: no         
    camion:
      name: camion
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter une name 
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory
        rule: no 
    isActive:
      name: isActive
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter isActive
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory
        rule: no 
    statut:
      name: Type
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter statut
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory
        rule: no

    livreur:
      name: livreur
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter une stations
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory
        rule: no 

    trajet:
      name: trajet
      type: text
      display:
        - show_table
        - show_form
      placeholder: Ajouter une stations
      rule: no
      required: yes 
      format:
        type: tab
        name: nocategory => nocategory
        rule: no 